### ISSUE TITLE
Feature request: 

### ISSUE THREAD

**Issue by camhunt** [WilsonBillkia/bane#2]
Very excited to see this! 

Would it be possible to incorporate the work that @thodges-gh has done in [this](https://github.com/thodges-gh/cldocker) project? Specifically the ability to select which eth client, specify ETH_URL, etc., while applying the hardening to the eth client, not just the chainlink.

**Comment by WilsonBillkia** [comment]
Hiya, 
Do you mean have an individual ansible ethereum role, using native ethereum node configuration? 
I've been meaning to do an ethereum version of this specifically, yes. Please elaborate a bit on what you would like to see.
Or is it the web front end which allows node configuration?

**Comment by camhunt** [comment]
The former. Really looking for an Ansible-driven deployment of both full eth node and chainlink.

**Comment by WilsonBillkia** [comment]
k, understood. I was looking at rolling this into the original script - should be trivial really. Give me a week or two and I'll see what I can do!

**Comment by WilsonBillkia** [comment]
NB, this is being worked on now, apologies for just leaving it for a while.

**Comment by WilsonBillkia** [comment]
Hi Ive done some testing and it builds an eth node - uses the eth PPA's and APT on Ubuntu server 20.x WIll push the code out before sop tomorrow.

**Comment by WilsonBillkia** [comment]
There is a vitalik.yml script that builds a geth node and installs nodejs as well (optional)
